export const GIR_COMPACT = "GIR0AA";
export const GIR_CANONICAL = "GIR 0AA";

export const FORBIDDEN_INWARD_LETTERS = "CIKMOV";
export const FORBIDDEN_FIRST_OUTWARD_LETTERS = "QVX";
export const FORBIDDEN_SECOND_OUTWARD_LETTERS = "IJZ";
export const AA9A_ALLOWED_FINAL_LETTERS = "ABEHMNPRVWXY";

export type OutwardPattern = "A9" | "A9A" | "A99" | "AA9" | "AA9A" | "AA99";
export type OutwardToken = "L" | "D" | "N";

export const OUTWARD_PATTERNS_BY_LENGTH: Readonly<Record<number, readonly OutwardPattern[]>> = {
  2: ["A9"],
  3: ["A9A", "A99", "AA9"],
  4: ["AA9A", "AA99"]
};

export const OUTWARD_PATTERN_TOKENS: Readonly<Record<OutwardPattern, readonly OutwardToken[]>> = {
  A9: ["L", "N"],
  A9A: ["L", "N", "L"],
  A99: ["L", "N", "D"],
  AA9: ["L", "L", "N"],
  AA9A: ["L", "L", "N", "L"],
  AA99: ["L", "L", "N", "D"]
};

export const AREA_SET: Readonly<Record<string, true>> = {
  AB: true,
  AL: true,
  B: true,
  BA: true,
  BB: true,
  BD: true,
  BF: true,
  BH: true,
  BL: true,
  BN: true,
  BR: true,
  BS: true,
  BT: true,
  BX: true,
  CA: true,
  CB: true,
  CF: true,
  CH: true,
  CM: true,
  CO: true,
  CR: true,
  CT: true,
  CV: true,
  CW: true,
  DA: true,
  DD: true,
  DE: true,
  DG: true,
  DH: true,
  DL: true,
  DN: true,
  DT: true,
  DY: true,
  E: true,
  EC: true,
  EH: true,
  EN: true,
  EX: true,
  FK: true,
  FY: true,
  G: true,
  GL: true,
  GU: true,
  GY: true,
  HA: true,
  HD: true,
  HG: true,
  HP: true,
  HR: true,
  HS: true,
  HU: true,
  HX: true,
  IG: true,
  IM: true,
  IP: true,
  IV: true,
  JE: true,
  KA: true,
  KT: true,
  KW: true,
  KY: true,
  L: true,
  LA: true,
  LD: true,
  LE: true,
  LL: true,
  LN: true,
  LS: true,
  LU: true,
  M: true,
  ME: true,
  MK: true,
  ML: true,
  N: true,
  NE: true,
  NG: true,
  NN: true,
  NP: true,
  NR: true,
  NW: true,
  OL: true,
  OX: true,
  PA: true,
  PE: true,
  PH: true,
  PL: true,
  PO: true,
  PR: true,
  RG: true,
  RH: true,
  RM: true,
  S: true,
  SA: true,
  SE: true,
  SG: true,
  SK: true,
  SL: true,
  SM: true,
  SN: true,
  SO: true,
  SP: true,
  SR: true,
  SS: true,
  ST: true,
  SW: true,
  SY: true,
  TA: true,
  TD: true,
  TF: true,
  TN: true,
  TQ: true,
  TR: true,
  TS: true,
  TW: true,
  UB: true,
  W: true,
  WA: true,
  WC: true,
  WD: true,
  WF: true,
  WN: true,
  WR: true,
  WS: true,
  WV: true,
  YO: true,
  ZE: true
};
